-- 코드를 입력하세요
# SELECT I.DATETIME, O.DATETIME, I.NAME,
#         DATEDIFF(O.DATETIME, I.DATETIME) AS PERIOD
# FROM ANIMAL_OUTS O JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
# ORDER BY PERIOD DESC
# LIMIT 2

SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS AS I, ANIMAL_OUTS AS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY ABS(O.DATETIME-I.DATETIME) DESC
LIMIT 2
