-- 코드를 입력하세요
# SELECT CATEGORY,
#         SALES AS TOTAL_SALES
# FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
# WHERE YEAR(S.SALES_DATE) = '2022' AND MONTH(S.SALES_DATE) = '01'
# GROUP BY B.CATEGORY
# ORDER BY CATEGORY

SELECT CATEGORY,
        SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY
