-- 코드를 입력하세요
# SELECT *,
#         IF('2022-10-16' BETWEEN START_DATE AND END_DATE, '대여중', '대여 가능') AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# # GROUP BY CAR_ID
# ORDER BY CAR_ID DESC

# SELECT CAR_ID, COUNT(*)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID

SELECT CAR_ID,
        IF(SUM(IF('2022-10-16' BETWEEN START_DATE AND END_DATE, 1, 0)), '대여중', '대여 가능') AS AVAILABLITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC